"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const core = require("./stream/core");
exports.core = core;
const zlib = require("./stream/zlib");
exports.zlib = zlib;
const gz = require("./stream/gz");
exports.gz = gz;
const zip = require("./stream/zip");
exports.zip = zip;
